name: build-macos

on:
  push:
    branches: [ "mtest" ]
  #pull_request:

jobs:
  build-macos:
    timeout-minutes: 30
    runs-on: ${{ matrix.config.os }}
    
    strategy:
      matrix:
        config:
          - {os: macos-14, arch: x86_64}
          - {os: macos-14, arch: arm64}

    steps:
    - name: Install dependencies
      run: |
        echo "begin..."
        brew install automake libtool pkg-config

    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Build Bitbi-Node
      env:
        ARCH: ${{ matrix.config.arch }}
      run: |
        # Set the correct host triple
        HOST="${ARCH}-apple-darwin"
        echo "Building for ${HOST}"

        cd depends
        NO_QT=1 NO_BDB=1 NO_USDT=1 make HOST=${HOST} ARCH=${{ matrix.config.arch }} V=1
        cd ..
        ./autogen.sh
        
        # Use the correct host triple for configuration
        ./configure --prefix=`pwd`/depends/${HOST} \
          --enable-cxx --enable-static --disable-shared \
          --with-pic --without-wallet --with-gui=no \
          --disable-tests --disable-bench \
          CXXFLAGS="-O2" \
          HOST=${HOST}
        
        mkdir -p depends/lib
        make V=1 -j$(sysctl -n hw.logicalcpu) src/bitbid
        chmod +x src/bitbid
        mv ./src/bitbid ./bitbid-${{ matrix.config.os }}-${ARCH}

    - name: Upload config.log
      if: failure() # Only run this step if a previous step failed
      uses: actions/upload-artifact@v2
      with:
        name: config.log-${{ matrix.config.os }}-${{ matrix.config.arch }}
        path: ./config.log

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: bitbid-${{ matrix.config.os }}-${{ matrix.config.arch }}
        path: ./bitbid-${{ matrix.config.os }}-${{ matrix.config.arch }}