name: build-macos

on:
  push:
    branches: [ "mtest" ]
  #pull_request:

jobs:
  build-macos:

    timeout-minutes: 30
    runs-on: ${{ matrix.config.os }}

    strategy:
      matrix:
        config:
          - {os: macos-11 }
          - {os: macos-12 }
          - {os: macos-13 }
          - {os: macos-14 }

    steps:
    - name: Install dependencies
      run: |
        echo "begin..."
        brew install automake libtool pkg-config 
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Build Bitbi-Node
      run: |
        cd depends
        NO_QT=1 NO_BDB=1 NO_WALLET=1 NO_USDT=1 make 
        cd ..
        ./autogen.sh
        # Capture the output
        full_triplet=$(./depends/config.guess)

        # Use parameter expansion to trim the version number
        generic_triplet="${full_triplet%%-*}-apple-darwin"

        # Echo the result
        echo $generic_triplet

        ./configure --prefix=`pwd`/depends/depends/$generic_triplet --enable-cxx --enable-static --disable-shared --with-pic --without-wallet --with-gui=no --disable-tests --disable-bench  CXXFLAGS="-O2"
        mkdir -p depends/lib
        make -j$(sysctl -n hw.logicalcpu) src/bitbid
        chmod +x src/bitbid
        mv ./src/bitbid ./bitbid-${{ matrix.config.os }}
    - name: Upload config.log
      if: failure() # Only run this step if a previous step failed
      uses: actions/upload-artifact@v2
      with:
        name: config.log
        path: ./config.log

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: bitbid-${{ matrix.config.os }}
        path: ./bitbid-${{ matrix.config.os }}