name: build-macos

on:
  push:
    branches: [ "mtest" ]
  pull_request:

jobs:
  build-macos:

    timeout-minutes: 5
    runs-on: ${{ matrix.config.os }}

    strategy:
      matrix:
        config:
          - {os: macos-13}

    steps:
    - name: Install dependencies
      run: |
        echo "begin..."
        brew install automake libtool boost pkg-config libevent llvm


    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Build Bitbi-Node
      run: |
        export CC=$(brew --prefix llvm)/bin/clang 
        export CXX=$(brew --prefix llvm)/bin/clang++
        echo "CC=$CC"
        echo "CXX=$CXX"
        ./autogen.sh
        ./configure --without-wallet --with-gui=no
        make -j src/bitbid

    - name: Upload config.log
      if: failure() # Only run this step if a previous step failed
      uses: actions/upload-artifact@v2
      with:
        name: config.log
        path: ./config.log
