name: build-windows-msys2

on:
  push:
    branches: [ "mtest" ]
  pull_request:

jobs:
  build-windows-msys2:

    timeout-minutes: 15
    runs-on: windows-latest

    strategy:
      matrix:
        config:
          - {c: "gcc", cxx: "g++", pow: 0.2.2,}

    defaults:
      run:
        shell: msys2 {0}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Setup MSYS2
      uses: eine/setup-msys2@v2
      with:
        update: true
        install: autoconf automake mingw-w64-x86_64-clang mingw-w64-x86_64-lld mingw-w64-x86_64-cmake make
          mingw-w64-x86_64-curl cmake ninja base-devel  mingw-w64-x86_64-boost 
          mingw-w64-x86_64-zeromq mingw-w64-x86_64-cppzmq libdb 
          mingw-w64-x86_64-miniupnpc mingw-w64-x86_64-zlib libevent mingw-w64-x86_64-libevent 
          mingw-w64-x86_64-toolchain libtool mingw-w64-x86_64-libtool mingw-w64-x86_64-libsodium
  
    - name: Install dependencies
      run: |
        echo "begin... pow ..."
        # download latest version of pow
        POW_URL="https://github.com/bitbi-core/pow/releases/download/v${{matrix.config.pow}}/windows-msys2-${{matrix.config.c}}.tar.gz"
        POW_HOME="$HOME/pow"
        mkdir -p $POW_HOME
        curl -L $POW_URL | tar xz -C $POW_HOME
        ls -l $POW_HOME

    - name: Build Bitbi-Node
      run: |
        export HOST=x86_64-w64-mingw32
        export PKG_CONFIG_PATH=/mingw64/lib/pkgconfig:$PKG_CONFIG_PATH
        export CPLUS_INCLUDE_PATH=/mingw64/include:$CPLUS_INCLUDE_PATH
        ./autogen.sh
        POW_HOME="$HOME/pow"
        ./configure CXXFLAGS="-I/mingw64/include -I/mingw64/include/c++/13.2.0 -I/mingw64/x86_64-w64-mingw32/include -I$POW_HOME/include" LDFLAGS="-L$POW_HOME/lib -L/mingw64/lib -lsodium -lrandomx" --prefix=/ --with-gui=no --with-wallet=no --disable-tests --disable-bench --disable-zmq
        mkdir -p depends/x86_64-pc-msys/lib
        make -j$(nproc) ./src/bitbid.exe
        mv ./src/bitbid.exe windows-msys2-bitbid-${{ matrix.config.c }}.exe

    - name: Upload config.log
      if: failure() # Only run this step if a previous step failed
      uses: actions/upload-artifact@v2
      with:
        name: config.log
        path: ./config.log

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: windows-msys2-bitbid-${{ matrix.config.c }}
        path: ./windows-msys2-bitbid-${{ matrix.config.c }}.exe